### ISSUE TITLE
Is sound abandoned in p5.js?

### ISSUE THREAD

**Issue by rahji** [processing/p5.sound.js#24]
### Most appropriate sub-area of p5.sound.js?

- [X] Accessibility
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [X] IO
- [ ] Math
- [ ] Utilities
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Steps to reproduce this

This is the replacement for the sound library but it appears to be unfinished and there have been no commits for 6 months (since the fellow responsible for it finished their fellowship). Meanwhile, the new p5.js reference website is missing any information/examples related to sound. And the github repo for the original sound library has been "sunsetted/archived/deprecated" before this new one is in place. Can someone explain what's happening?

**Comment by Qianqianye** [comment]
Hi @rahji. We are actively working on the new p5.sound library in [this repo](https://github.com/processing/p5.sound.js-pre-release). We are planning to have more updates on the release of the new p5.sound library in a month or so. I will close this issue for now. Feel free to reopen it if you have additional questions. Thank you!
