### ISSUE TITLE
Thoughts on p5. prefix for classes?

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.sound.js#31]
Right now new classes are made like `new Oscillator()`. Currently in p5, other class names have a `p5.` prefix (e.g. `p5.Graphics`) and are made with a `create*` function (e.g. `createGraphics()`).

Do you think it's worth having consistency in this library too? For p5 2.0 we're also adding some more standardization around addons and how they add classes to the namespace so that they can work in both global and instance mode. When 2.0 is more stable, would it be worth trying to expose these classes and methods using that addon structure?

cc @limzykenneth

**Comment by limzykenneth** [comment]
For this version of the library, let's go with whatever matches the previous version of p5.sound. The `createX()` type signature is definitely good to have for consistency and it is merely using factory functions instead of constructor pattern so it still a good pattern to use.

**Comment by ogbabydiesal** [comment]
agreed adding the p5 prefix will ensure more backwards compatibility with sketches/teaching material and examples made using the old library

**Comment by ogbabydiesal** [comment]
added
