### ISSUE TITLE
Current state of P5JS Sound?

### ISSUE THREAD

**Issue by paul-uz** [processing/p5.sound.js#35]
I'm coming back to some old P5JS projects that were using the sound library, and things have moved on a bit.

Lot of dead links and seemingly no info on the sound library on the P5JS website; whats going on? Whats the current state of P5JS and P5JS Sound?

**Comment by ogbabydiesal** [comment]
hi @paul-uz we are revamping the p5 sound library and will be releasing that very soon - hence all the activity in this repo, more soon!

**Comment by paul-uz** [comment]
@ogbabydiesal Is there a rough ETA?
