### ISSUE TITLE
Add docs to userStartAudio + other utils

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.sound.js#40]
In the old p5.sound library, we had these docs: https://archive.p5js.org/reference/#/p5/userStartAudio

I think we still have it here, but just without doc comments: https://github.com/processing/p5.sound.js/blob/064f415f6011fe8cbb610bc86c0db07e2defcad2/src/Utils.js#L17-L19

It would maybe be good to add those docs + examples back (and possibly for the other utils in that file too, like [getAudioContext](https://archive.p5js.org/reference/#/p5/getAudioContext))

cc @Qianqianye

**Comment by Qianqianye** [comment]
Thanks @davepagurek. Hi @ogbabydiesal, could you double check if we have any other missing documents besides userStartAudio?

**Comment by ogbabydiesal** [comment]
docs added 🤙
