### ISSUE TITLE
Possible typo in module name

### ISSUE THREAD

**Issue by nickmcintyre** [processing/p5.sound.js#41]
Hello! Very excited to try the new sound library -- a friend and I are taking some inspiration from Imogen Heap's [gloves](https://www.youtube.com/watch?v=3QtklTXbKUQ&t=554s).

I was perusing the repo when I came across [PitshShifter.js](https://github.com/processing/p5.sound.js/blob/main/src/PitshShifter.js). Should this file be named `PitchShifter.js` given the class it exports?

**Comment by ogbabydiesal** [comment]
fixed thanks @nickmcintyre !
