### ISSUE TITLE
Need a method to adjust noise amplitude

### ISSUE THREAD

**Issue by Metamere** [processing/p5.sound.js#42]
In the reference on [the reference docs](https://p5js.org/reference/p5.sound/p5.Noise/) it lists a method for adjusting the amplitude of the noise source, but when I tried using noise.amp(0.25) it has an error and does not work. I looked in the p5.sound.js source code and it appears that there is no such method for the noise class.

**Comment by ogbabydiesal** [comment]
good catch fixed here: https://github.com/processing/p5.sound.js/commit/d42195a799944826c4f3708297c98497d3f7d4d8

🫡
